fix: DTA-79: update `disableDraftSpecs` property name
detra-lab/esbuild-plugin-lit-css pull request #27
Opened 2023-11-16 09:38 UTC by rosdb

2023-11-16 13:51 UTC, giotramu commented on .changeset/many-schools-smile.md
> +The property name disableDraftSpecs is misleading. It has been changed to includeDraftSpecs.
```suggestion
The property name `disableDraftSpecs` is misleading. It has been changed to `includeDraftSpecs`.
```

2023-11-16 14:03 UTC, giotramu requested changes

2023-11-16 14:03 UTC, giotramu commented on src/index.ts
>     * You may disable them to speed up the process.
This message should be changed to:

```ts
/**
 * Lightning CSS compiles [specifications](https://lightningcss.dev/transpilation.html#draft-syntax) not yet 
 * available in browsers. You can include them and avoid transpilation to speed up the process.
 * Default: `false`.
 */
```

2023-11-16 14:06 UTC, giotramu commented on src/core/css-bundler.ts
> +  isDraftSyntaxIncluded
Here, we can use a similar namespace:

```suggestion
  isDraftSpecsIncluded
```

Thoughts?

2023-11-16 16:51 UTC, rosdb commented on src/core/css-bundler.ts
> +  isDraftSyntaxIncluded
Let us use the naming used by Lightning CSS, `Draft Syntax`, and update the property too. WDYT? @giotramu

2023-11-16 22:09 UTC, giotramu commented on src/core/css-bundler.ts
> +  isDraftSyntaxIncluded
Sticking to the _Specs_ namespace is better, as this is the [official terminology](https://www.w3.org/Style/CSS/specs.en.html) used by the W3C.

So I suggest `isDraftSpecsIncluded` and `includeDraftSpecs`.

2023-11-17 08:41 UTC, rosdb commented
@giotramu, requests have been handled! ✅

2023-11-17 16:15 UTC, giotramu approved these changes

2023-11-17 16:36 UTC, merged